services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
    api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        image: docker.io/nikil1121/simple_blog_api
        environment:
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=simple_blog_api
        ports:
          - "3000:3000"

