services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build:
            context: ./server
        image: docker.io/nikil1121/complex_api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
      build: 
        context: ./worker
      image: docker.io/nikil1121/complex_worker
      environment:
          - REDIS_HOST=redis
          - REDIS_PORT=6379
    client:
      build: 
        context: ./client
      image: docker.io/nikil1121/complex_client
    nginx:
      depends_on:
        - api
        - client
      build: ./nginx
      ports:
        - "8082:80"
