apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api-app
          image: docker.io/nikil1121/simple_blog_api
          resources:
            limits:
                  memory: "256Mi"
                  cpu: "1"
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: "5432"  
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: simple_blog_api
